steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'server/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/dealforge-core:$COMMIT_SHA', 'server']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/dealforge-core:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/dealforge-core:$COMMIT_SHA']
