/**
 * Audit Event Types
 *
 * Centralized enum of all auditable events in DealForge.
 */
const EVENT_TYPES = {
  DEAL_STATE_UPDATED: 'DEAL_STATE_UPDATED',
  TOOL_EXECUTED: 'TOOL_EXECUTED',
  POLICY_CHECKED: 'POLICY_CHECKED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  APPROVAL_RESOLVED: 'APPROVAL_RESOLVED',
  ESCALATION_TRIGGERED: 'ESCALATION_TRIGGERED',
  CALL_STARTED: 'CALL_STARTED',
  CALL_ENDED: 'CALL_ENDED',
  CALL_FAILED: 'CALL_FAILED',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_WEBHOOK_RECEIVED: 'AGENT_WEBHOOK_RECEIVED',
  AGENT_RESPONSE_COMPLETED: 'AGENT_RESPONSE_COMPLETED',
  AGENT_AUDIO_PUBLISHED: 'AGENT_AUDIO_PUBLISHED',
  CUSTOMER_AUDIO_PLAYBACK_STARTED: 'CUSTOMER_AUDIO_PLAYBACK_STARTED',
  CUSTOMER_AUDIO_PLAYBACK_FAILED: 'CUSTOMER_AUDIO_PLAYBACK_FAILED',
  AGENT_AUDIO_TIMEOUT: 'AGENT_AUDIO_TIMEOUT',
  EVIDENCE_EXTRACTED: 'EVIDENCE_EXTRACTED',
  NEGOTIATION_MEMORY_RECORDED: 'NEGOTIATION_MEMORY_RECORDED',
  CONVERSATION_STAGE_CHANGED: 'CONVERSATION_STAGE_CHANGED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  NEXT_BEST_ACTION_UPDATED: 'NEXT_BEST_ACTION_UPDATED',
  DEAL_HEALTH_CALCULATED: 'DEAL_HEALTH_CALCULATED',
  ACTION_PLAN_CREATED: 'ACTION_PLAN_CREATED',
  ACTION_PLAN_COMPLETED: 'ACTION_PLAN_COMPLETED',
  EXTERNAL_ACTION_FAILED: 'EXTERNAL_ACTION_FAILED',
  POST_CALL_AUTOPILOT_COMPLETED: 'POST_CALL_AUTOPILOT_COMPLETED',
  AGENT_RESPONSE_FAILED: 'AGENT_RESPONSE_FAILED',
};

module.exports = { EVENT_TYPES };
