require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const path = require('path');
const request = require('supertest');
const assert = require('node:assert/strict');
const { createApp } = require(path.join(__dirname, '..', 'src', 'app'));
const { createCallSession } = require(path.join(__dirname, '..', 'src', 'lib', 'calls', 'callSessions'));
const { getHistory } = require(path.join(__dirname, '..', 'src', 'lib', 'agent', 'conversationHistory'));
const { db } = require(path.join(__dirname, '..', 'src', 'lib', 'firebase', 'admin'));

async function run() {
  console.log('===============================================================');
  console.log('DEALFORGE VOICE PIPELINE END-TO-END INTEGRATION TEST');
  console.log('===============================================================');
  const timestamps = {};
  timestamps.test_start = new Date().toISOString();

  // Ensure SARVAM_API_KEY is present
  if (!process.env.SARVAM_API_KEY) {
    const { execSync } = require('child_process');
    try {
      process.env.SARVAM_API_KEY = execSync('gcloud secrets versions access latest --secret=dealforge-sarvam-api-key --project=dealforge-507515', { encoding: 'utf8' }).trim();
      console.log('✓ Retrieved SARVAM_API_KEY from Secret Manager');
    } catch (e) {
      console.warn('Could not read from secret manager, using env if set');
    }
  }

  // 1. Get an existing deal or pick first deal in Firestore
  const dealsSnap = await db.collection('deals').limit(1).get();
  if (dealsSnap.empty) {
    console.error('FAIL: No deals found in Firestore');
    process.exit(1);
  }
  const dealDoc = dealsSnap.docs[0];
  const dealId = dealDoc.id;
  const orgId = dealDoc.data().organizationId;
  console.log(`[Stage 1: Session Init] Found deal: ${dealId} (org: ${orgId})`);

  // 2. Create a verified call session
  const { session, linkToken } = await createCallSession({
    organizationId: orgId,
    dealId,
    managerId: 'test-manager',
    customerLabel: 'Voice Test Customer',
    expiresInMinutes: 60
  });
  console.log(`[Stage 1: Session Created] sessionId: ${session.sessionId}, linkToken: ${linkToken.slice(0, 8)}...`);
  timestamps.session_created = new Date().toISOString();

  const app = createApp();

  // 3. Test Join with openai_realtime provider
  process.env.VOICE_PROVIDER = 'openai_realtime';
  timestamps.join_start = new Date().toISOString();
  const joinRes = await request(app)
    .post(`/api/public/calls/${encodeURIComponent(linkToken)}/join`)
    .send({});
  timestamps.join_completed = new Date().toISOString();

  assert.equal(joinRes.status, 200, `Join failed: ${JSON.stringify(joinRes.body)}`);
  assert.equal(joinRes.body.voiceProvider, 'openai_realtime');
  assert.ok(joinRes.body.clientSecret, 'OpenAI Realtime ephemeral clientSecret must be returned');
  assert.match(joinRes.body.clientSecret, /^ek_/, 'clientSecret must start with ek_');
  assert.ok(joinRes.body.sessionCredential, 'DealForge sessionCredential must be returned');
  const sessionCredential = joinRes.body.sessionCredential;
  console.log(`[Stage 2: Customer Join] OK (provider: ${joinRes.body.voiceProvider}, clientSecret: ${joinRes.body.clientSecret.slice(0, 8)}..., status: ${joinRes.status})`);

  // 4. Test Ready / Greeting
  timestamps.greeting_start = new Date().toISOString();
  const readyRes = await request(app)
    .post(`/api/public/calls/${encodeURIComponent(linkToken)}/ready`)
    .send({ sessionCredential });
  timestamps.greeting_completed = new Date().toISOString();

  assert.equal(readyRes.status, 202);
  assert.equal(readyRes.body.status, 'GREETING_REQUESTED');
  assert.ok(readyRes.body.greeting);
  assert.ok(readyRes.body.audioBase64, 'Greeting audioBase64 should be generated by Sarvam TTS');
  const greetingWavBytes = Buffer.from(readyRes.body.audioBase64, 'base64');
  assert.equal(greetingWavBytes.slice(0, 4).toString('ascii'), 'RIFF', 'Audio must be valid RIFF WAV');
  console.log(`[Stage 3: Greeting Spoken] OK (${greetingWavBytes.length} bytes WAV, text: "${readyRes.body.greeting}")`);

  // 5. Simulate Customer Utterance:
  // "Hello, I have a sales team and I want to know your pricing."
  const customerSpeech = "Hello, I have a sales team and I want to know your pricing.";
  console.log(`\n[Stage 4: Customer Speech] Customer says: "${customerSpeech}"`);
  timestamps.turn_request_start = new Date().toISOString();

  const turnRes = await request(app)
    .post(`/api/public/calls/${encodeURIComponent(linkToken)}/turn`)
    .send({
      sessionCredential,
      userText: customerSpeech
    });
  timestamps.turn_request_completed = new Date().toISOString();

  assert.equal(turnRes.status, 200, `Turn request failed: ${JSON.stringify(turnRes.body)}`);
  assert.equal(turnRes.body.userText, customerSpeech);
  assert.ok(turnRes.body.assistantText, 'Assistant text must not be empty');
  console.log(`[Stage 5: Gemini & Core Runtime] OK! Assistant responded:`);
  console.log(`  "${turnRes.body.assistantText}"`);

  // Verify Sarvam TTS audio in response
  assert.ok(turnRes.body.audioBase64, 'Turn audioBase64 must be synthesized by Sarvam');
  const answerWavBytes = Buffer.from(turnRes.body.audioBase64, 'base64');
  assert.equal(answerWavBytes.slice(0, 4).toString('ascii'), 'RIFF', 'Assistant audio must be valid RIFF WAV');
  console.log(`[Stage 6: Sarvam Voice Output] OK! Generated ${answerWavBytes.length} bytes of WAV audio (Ishita)`);

  // Verify Firestore history persistence
  const history = await getHistory(session.sessionId);
  const userMsg = history.find(m => m.role === 'user');
  const assistantMsg = history.find(m => m.role === 'assistant' && m.content === turnRes.body.assistantText);
  assert.ok(userMsg, 'User message must be in Firestore conversation history');
  assert.ok(assistantMsg, 'Assistant message must be in Firestore conversation history');
  console.log(`[Stage 7: Firestore Durability] OK! History contains ${history.length} messages.`);

  // 6. Stop call
  timestamps.stop_start = new Date().toISOString();
  const stopRes = await request(app)
    .post(`/api/public/calls/${encodeURIComponent(linkToken)}/stop`)
    .send({ sessionCredential });
  timestamps.stop_completed = new Date().toISOString();
  assert.equal(stopRes.status, 200);
  console.log(`[Stage 8: Call Stop] OK (status: ${stopRes.body.status})`);

  console.log('\n===============================================================');
  console.log('TIMESTAMPS FOR EACH STAGE:');
  console.log('===============================================================');
  for (const [k, v] of Object.entries(timestamps)) {
    console.log(`  ${k.padEnd(26)} : ${v}`);
  }
  console.log('===============================================================');
  console.log('✅ ALL STAGES PASSED VERIFICATION WITH CONCRETE EVIDENCE');
  console.log('===============================================================');
  process.exit(0);
}

run().catch(err => {
  console.error('FAIL:', err);
  process.exit(1);
});
